# Build the FOSS "minimal" flavor of the Home Assistant Companion app, which
# contains no Google Play Services code.
#
# The Google Services Gradle plugin is still applied to every app variant
# (build-logic/convention/.../AndroidApplicationConventionPlugin.kt) and fails
# without a google-services.json, even for minimal. The placeholder file the
# project's own CI uses is enough to satisfy it; see
# .github/actions/setup-build-env/action.yml. google-services.json is
# gitignored, so the copies never show up in git.

ADB ?= adb
ADB_SERIAL ?=
ADB_TARGET = $(if $(ADB_SERIAL),-s $(ADB_SERIAL))
GRADLE_USER_HOME ?= $(CURDIR)/gradle-cache
export GRADLE_USER_HOME

# Debug builds enable StrictMode and crash on any violation that is not
# explicitly ignored. Some OEM ROMs trip violations inside framework code (e.g.
# Samsung's BluetoothManager constructor reading from disk on the main thread),
# which makes the app crash on launch on those phones. -PnoStrictMode sets
# BuildConfig.NO_STRICT_MODE so it stays off. Override with GRADLE_FLAGS= to
# get upstream's StrictMode behavior back.
GRADLE_FLAGS ?= -PnoStrictMode
GRADLEW = ./gradlew $(GRADLE_FLAGS)

MOCK_GOOGLE_SERVICES = .github/mock-google-services.json

APP_DEBUG_APK = $(CURDIR)/app/build/outputs/apk/minimal/debug/app-minimal-debug.apk
WEAR_DEBUG_APK = $(CURDIR)/wear/build/outputs/apk/debug/wear-debug.apk
AUTOMOTIVE_DEBUG_APK = $(CURDIR)/automotive/build/outputs/apk/minimal/debug/automotive-minimal-debug.apk

# Generated by set-real-hass-cert.sh and not tracked by git. Gradle already
# fails without them, but only with a resource-linking error.
PRIVATE_CA_FILES = \
	app/src/main/res/raw/homelab_ca.pem \
	app/src/main/res/xml/network_security_config.xml \
	wear/src/main/res/raw/homelab_ca.pem \
	wear/src/main/res/xml/network_security_config.xml

.PHONY: build test install-debug \
	wear wear-test wear-install-debug \
	automotive automotive-test automotive-install-debug \
	private-ca-check clean stop

# --- Phone app (minimal flavor) ---------------------------------------------

build: private-ca-check app/google-services.json
	$(GRADLEW) :app:assembleMinimalDebug

test: private-ca-check app/google-services.json
	$(GRADLEW) :app:testMinimalDebugUnitTest :app:lintMinimalDebug

install-debug:
	@test -f "$(APP_DEBUG_APK)" || { echo "Debug APK not found: $(APP_DEBUG_APK)" >&2; exit 1; }
	$(ADB) $(ADB_TARGET) install -r "$(APP_DEBUG_APK)"

# --- Wear OS (no flavors, so there is no separate minimal variant) ----------

wear: private-ca-check wear/google-services.json
	$(GRADLEW) :wear:assembleDebug

wear-test: private-ca-check wear/google-services.json
	$(GRADLEW) :wear:testDebugUnitTest :wear:lintDebug

wear-install-debug:
	@test -f "$(WEAR_DEBUG_APK)" || { echo "Debug APK not found: $(WEAR_DEBUG_APK)" >&2; exit 1; }
	$(ADB) $(ADB_TARGET) install -r "$(WEAR_DEBUG_APK)"

# --- Android Automotive (minimal flavor) ------------------------------------

automotive: private-ca-check automotive/google-services.json
	$(GRADLEW) :automotive:assembleMinimalDebug

automotive-test: private-ca-check automotive/google-services.json
	$(GRADLEW) :automotive:testMinimalDebugUnitTest :automotive:lintMinimalDebug

automotive-install-debug:
	@test -f "$(AUTOMOTIVE_DEBUG_APK)" || { echo "Debug APK not found: $(AUTOMOTIVE_DEBUG_APK)" >&2; exit 1; }
	$(ADB) $(ADB_TARGET) install -r "$(AUTOMOTIVE_DEBUG_APK)"

# --- Housekeeping -----------------------------------------------------------

private-ca-check:
	@for f in $(PRIVATE_CA_FILES); do \
		test -f "$$f" || { echo "error: $$f is missing; run ./set-real-hass-cert.sh path/to/fullchain.pem (again after a rebase)" >&2; exit 1; }; \
	done

# No prerequisites, so make only copies the placeholder when the file is
# missing and never overwrites a real google-services.json dropped in by hand.
app/google-services.json wear/google-services.json automotive/google-services.json:
	cp "$(MOCK_GOOGLE_SERVICES)" "$@"

clean:
	$(GRADLEW) clean

# Stop Gradle daemons. Run this after rebuilding the dev container image, or a
# daemon left over from the old container can keep serving builds against the
# old SDK.
stop:
	$(GRADLEW) --stop
